[env:uno]
platform = atmelavr
board = uno
build_flags = 
    -Os
    -Wl,-u,vfprintf -lprintf_flt -lm
upload_protocol = custom
upload_command = avrdude -p m328p -c xplainedmini -P usb -U flash:w:$SOURCE:i